services:
  oag-tracker:
    image: ghcr.io/j-wendoh/status-tracker-v2:latest
    container_name: oag-tracker-app
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - oag-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  oag-network:
    driver: bridge